export const BIKE_REPOSITORY = 'BIKE_REPOSITORY';
export const MAINTENANCE_REPOSITORY = 'MAINTENANCE_REPOSITORY';
export const MAINTENANCE_NOTIFICATION_REPOSITORY =
  'MAINTENANCE_NOTIFICATION_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
