export const BIKE_MODEL_REPOSITORY = 'BIKE_MODEL_REPOSITORY';
export const MAINTENANCE_SCHEDULE_REPOSITORY =
  'MAINTENANCE_SCHEDULE_REPOSITORY';
export const MAINTENANCE_NOTIFICATION_REPOSITORY =
  'MAINTENANCE_NOTIFICATION_REPOSITORY';
