version: "3.8"
services:
  nest:
    build:
      context: .
      dockerfile: infrastructure/platforms/nest/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  express:
    build:
      context: ./infrastructure/platforms/express
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/triumphrental
      - NODE_ENV=development
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - nest
      - express
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: triumph_fleet_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: triumph_fleet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d triumph_fleet"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
